options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  brace-style:
    - 2
    - allow-single-line: true
  extends-before-declarations: 2
  extends-before-mixins: 2

  # Mixins
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    - additional-identifiers: []
      excluded-identifiers: []

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  id-name-format:
    - 2
    - convention: hyphenatedlowercase
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase

  # Style Guide
  bem-depth:
    - 0
    - max-depth: 2
  border-zero:
    - 2
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 2
    - include: false
  nesting-depth:
    - 2
    - max-depth: 3
  property-sort-order:
    - 0
    - ignore-custom-properties: false
  property-units:
    - 2
    ######
    # Font-relative lengths:        ch, em, ex, rem
    # Absolute lengths:             cm, in, mm, pc, pt, px, q
    # Viewport-percentage lengths:  vh, vw, vmin, vmax
    # Angles:                       deg, grad, rad, turn
    # Durations:                    Hz, kHz
    # Frequencies:                  dpi, dpcm, dppx
    # Resolutions:                  %
    ######
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property:
        font-size: ['em', 'rem']
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
  url-quotes: 2
  variable-for-property:
      - 0
      - properties: []
  zero-unit: 2

  # Inner Spacing
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false

  # Final Items
  final-newline:
    - 2
    - include: true
  trailing-semicolon: 2