sudo: false
language: go
go:
  - master
env:
  - VERSION=0.39
install: 
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - wget https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz
  - tar xvzf hugo_${VERSION}_Linux-64bit.tar.gz
  - mkdir -p $GOPATH/bin
  - cp hugo_${VERSION}_Linux-64bit/hugo $GOPATH/bin/hugo
script:
  - npm test
  - npm run build:prod
branches:
  only: 
    - master
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: lSfUsHfUzWtuAl6pGJYDH5UvLVqV02iopGrh7iYJpW2t72DI3A05kP7tVYdug3Qjhe6VD6mFP1HYTg/gD0u26mP83t2dj7UXHn9W5/8GGZGnPXcdAR6bJAhqKhOC31QehYbq1TMiUvRBcn9W0nND0pyZwzNR4jruQHMrVwB1rQ+H83AzydBNfeLablWwzA8TCyJo2pmkXOoPrnWsM0Wox7rknpm5gw91iRnrnKOK+ml1QnGyazpTZBnPu5guxq1ynCwhJPGHxuN65ipqqJ9K/yYbDl+SKtTdPyOHUgoJr5S4Wi5eVLLpJPkEK2VyCCRcVW+69X6kvX/WXFaWU2c2K5qapui1cYMfXwTce0RdrIJSqB/xeIsKGp+8HZA4CTyqAY4mIhxbNwbeVULqfXbp3gXnwMab15iXNXsSnFWKsySymVIkhb/vCvwuqeM5DLSf+CoNJ/1VQB3+ZcroXLHWim336qsxbxXa4x69x3vIkrVxCKChtNS/VVPlkYJIJWTAZYwEyhGFTU+i3NLdUIpoUyl0aNEy6WizD0O/Q7w6y/oHFRSR8IaVIzhBhmkgbx9bsMVLm63dOYQAiBNe0osEH94cpPLCJLpYzWMsxk39HpbWSjIUae4KlqleJVFjk339cE9d3ZrC2W/CG8eYZG5lnNqFM/LxmCO3Bp6gEgAkfZE=
  on:
    branch: master